<a href="https://colab.research.google.com/github/Rajulearner/__tensorflow__/blob/master/ANN_with_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



What is **ANN**?<br>


> Artificial Neural Networks (ANN) is a supervised learning system built of a large number of simple elements, called neurons or perceptrons. Each neuron can make simple decisions, and feeds those decisions to other neurons, organized in interconnected layers.





> <i>The basic functioning of Artificial Neural Net(ANN) is inspired by working of biological neuron. Human brain learns as a result of getting trained by sample data initially. For example, we learn to call a fruit-apple after initally getting “trained” to see the apple as object in real life or it’s image.</i>





> The most simple neural network is the <b> “perceptron”</b>, which, in its simplest form, consists of a single neuron. Much like biological neurons, which have dendrites and axons, the single artificial neuron is a simple tree structure which has input nodes and a single output node, which is connected to each input node.</b>
<br><br>



#Shallow vs Deep Neural network



> In <b>Shallow Neural network</b>, there will be only one <i> hidden</i> layer between input and output layers.


> In <b> Deep Neural network</b> , there will more than one <i> hiddden </i> layers between input and output layers.
<hr><hr><br><br>
<img src="https://missinglink.ai/wp-content/uploads/2018/11/networkgraph-1.png"></img>
<br><br><br>

**What is Activation Function?** 



If we do not apply a Activation function then the output signal would simply be a simple linear function.A linear function is just a polynomial of one degree. Now, a linear equation is easy to solve but they are limited in their complexity and have less power to learn complex functional mappings from data. A Neural Network without Activation function would simply be a Linear regression Model, which has limited power and does not performs good most of the times



*   Sigmoid
*   Tanh

*   ReLu
*   LeakyReLu
<br><br><br>







**What is Back Propagation?**



1.   First in forward propagation the weights get updated (some random values) and nodes get updated(hidden layer) and we get final output. Now it checks the output with true value, If there is large error "the Loss Function calculate these errors and gives feedback to 'weights' by using the back propagation.
2.   By using Back-propagation technique we change the "weights" and try to reduce the "errors" in next iteration(epoch). <br><br>
<img src="https://www.guru99.com/images/1/030819_0937_BackPropaga1.png"></img>

<br>
<br>
<br>
<br>


**Steps for building your first ANN**
<li>
Data Preprocessing<br><li>
Add input layer<br><li>
Random w init<br><li>
Add Hidden Layers<br><li>
Select Optimizer, Loss, and Performance Metrics<br><li>
Compile the model<br><li>
use model.fit to train the model<br><li>
Evaluate the model<br><li>
Adjust optimization parameters or model if needed</li>


In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [11]:
from google.colab import files
uploaded = files.upload()

Saving datasets_13214_17927_Churn_Modelling.csv to datasets_13214_17927_Churn_Modelling.csv


In [12]:
print (uploaded['datasets_13214_17927_Churn_Modelling.csv'][:200].decode('utf-8') + '...')

RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,15634602,Hargrave,619,France,Female,42,2,0,1,1,1,101348.88...


In [13]:
import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['datasets_13214_17927_Churn_Modelling.csv'].decode('utf-8')))
df

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [15]:
x=df.drop(labels=['RowNumber','CustomerId','Surname','Exited'],axis=1)
y=df['Exited']
x.head(),y

(   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
 0          619    France  Female  ...          1               1        101348.88
 1          608     Spain  Female  ...          0               1        112542.58
 2          502    France  Female  ...          1               0        113931.57
 3          699    France  Female  ...          0               0         93826.63
 4          850     Spain  Female  ...          1               1         79084.10
 
 [5 rows x 10 columns], 0       1
 1       0
 2       1
 3       0
 4       0
        ..
 9995    0
 9996    0
 9997    1
 9998    1
 9999    0
 Name: Exited, Length: 10000, dtype: int64)

In [16]:
#data preprocessing
from sklearn.preprocessing import LabelEncoder

In [18]:
label = LabelEncoder()
x['Geography']=label.fit_transform(x['Geography'])
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [19]:
label1 = LabelEncoder()
x['Gender']=label1.fit_transform(x['Gender'])
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [ ]:
#applying one-hot encoding to geography bcz of numerical importance
x=pd.get_dummies(x,drop_first=True,columns=['Geography'])


In [34]:
x.shape[1]

11

#**Feature** **Standardization**

In [22]:
from sklearn.preprocessing import StandardScaler



In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [25]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [26]:
x_train,x_test

(array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
         -0.5698444 ,  1.74309049],
        [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
          1.75486502, -0.57369368],
        [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
         -0.5698444 , -0.57369368],
        ...,
        [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
         -0.5698444 , -0.57369368],
        [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
         -0.5698444 ,  1.74309049],
        [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
          1.75486502, -0.57369368]]),
 array([[-0.56129438, -1.11339196, -0.39401698, ...,  1.62185911,
          1.62776996, -0.57427105],
        [-1.33847768, -1.11339196,  0.07611425, ...,  0.504204  ,
         -0.61433742, -0.57427105],
        [ 0.58347561, -1.11339196,  0.26416674, ..., -0.41865644,
         -0.61433742,  1.74133801],
        ...,
        [-0.76084144,  0.8981563 , -0.29999074, ...,  

# **Building ANN**

In [42]:
model = Sequential()
#x.shape[1]:will give us the shape of i/p layer
model.add(Dense(x.shape[1], activation='relu',input_dim = x.shape[1]))#input layer
model.add(Dense(128, activation='relu'))#hidden layer
model.add(Dense(1,activation='sigmoid'))#activation function -- sigmoid

In [43]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#we can use gradient optimizers too but it will take more time 
#loss func --since this is just a binary_cross entropy, otherwise we use some other functions

In [44]:
#training
#since x_train is a numpy array , convert y_train to numpy array(i havent seen much diff even if we don't use)
model.fit(x_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose=1)
#more epochs will overfits the model
#verbose---progress bar
#batch-size-->if batch size is '1' it will take more time to load(since it checks or calculates the weights with each and every possible thing ).
#genearlly we give batch sizes as size of i/p layers for faser calculaions

Epoch 1/10
800/800 [==============================] - 1s 1ms/step - loss: 0.4387 - accuracy: 0.8077
Epoch 2/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3751 - accuracy: 0.8413
Epoch 3/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3595 - accuracy: 0.8481
Epoch 4/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3528 - accuracy: 0.8539
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3480 - accuracy: 0.8551
Epoch 6/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3453 - accuracy: 0.8568
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3434 - accuracy: 0.8570
Epoch 8/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3397 - accuracy: 0.8597
Epoch 9/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3381 - accuracy: 0.8590
Epoch 10/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3367 - accuracy: 0.8627

In [45]:
y_pred = model.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [46]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [47]:
y_test#xheck with above values to check

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [48]:
model.evaluate(x_test,y_test)#accuracy

63/63 [==============================] - 0s 1ms/step - loss: 0.3397 - accuracy: 0.8605


[0.33969107270240784, 0.8604999780654907]

In [49]:
#another way to cal accuracy
from sklearn.metrics import confusion_matrix,accuracy_score

In [51]:
confusion_matrix(y_test, y_pred)

array([[1525,   70],
       [ 209,  196]])

In [52]:
accuracy_score(y_test,y_pred)

0.8605